/*시퀀스 : 하나의 객체, 동시 작성시 중복되는 것을 방지*/

/*게시판 생성관련 시퀀스 생성 */
CREATE SEQUENCE BOARD
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE;


CREATE TABLE BOARD(
  ID VARCHAR2(30) NOT NULL PRIMARY KEY,
, TITLE VARCHAR2(100) NOT NULL
, CONTENT BLOB NOT NULL
, SYSDATE DATE NOT NULL
, NUM NUMBER NOT NULL
, READCNT NUMBER NOT NULL
, PW STRING NOT NULL
);
